eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      weight: 50
server:
  port: 8762
spring:
  application:
    name: eureka-client
  zipkin:
    base-url: http://localhost:9411